### PR TITLE
fix: update title and description for new name

### PR DESCRIPTION
**Pull request by Porkepix**
Fixing long description and title for fastlane which wasn't updated, and cause F-droid to still use old name despite updated metadata (see https://f-droid.org/fr/packages/org.bitbatzen.wlanscanner/ for example).

Also, out of curiosity on my end, why the name change?

And little nitpick from me, but I saw in the short description it uses "Analyse", which is generally GB English while US rather write "Analyze", but it's put in the `en_US` fastlane locale.
But you might prefer that spelling and don't want to bother separating `en_US` and `en_GB` :)

### CODE REVIEW

**Comment by bewue** [comment]
As far as I can remember it has always been like this with the name. For the German speaking countries **WLANScanner** and for the rest of the world **WiFiScanner**. I think in most countries the term **Wi-Fi** is more common, except e.g. in Germany. The distinction exist to let the people find the app better in the search.

I only maintain the English and German translation. So yes, small differences between en_US and en_GB are negligible for me, as long as it is well understood :)

**Comment by Porkepix** [comment]
> As far as I can remember it has always been like this with the name. For the German speaking countries **WLANScanner** and for the rest of the world **WiFiScanner**. I think in most countries the term **Wi-Fi** is more common, except e.g. in Germany. The distinction exist to let the people find the app better in the search.

Mmmmh, I thought it used to be listed as "WiFiScanner" on my phone, and recently switched to WLANScanner. I might remember wrongly though and be wrong about that.

But it's very unsettling that the application is listed as "WiFiScanner" within F-droid, and once you install it, it appears with a different name. Whether it is WLANScanner or WiFiScanner, I do think that English version of both should match (or same goes for other languages, for that matter).

**Comment by bewue** [comment]
Well, ok :) ...changes will be included in the next release.

**Comment by Porkepix** [comment]
> Well, ok :) ...changes will be included in the next release.

Well, you know better, for sure WiFi is much more commonly used than WLAN (you never know if you should look for WiFi, Wi-Fi, wifi etc. though), but my point was just to standardize the same wording everywhere. But the wording could also well be WiFi :)

**Pull request merged**
